id = "bearded-icon-tokyo-theme"
name = "Bearded Icon Tokyo Theme"
version = "0.3.0"
schema_version = 1
authors = ["Kris van der Ven"]
description = "Bearded icon theme for Zed with Tokyo color scheme"
repository = "https://github.com/kjvdven/bearded-icons-tokyo-theme.git"
